[L0]
submitterID = 'OTC'
creator = 'http://meta.icos-cp.eu/resources/organizations/CarbonPortal_CreatorSite'
contributors = '[]'
hostOrganization = 'http://meta.icos-cp.eu/resources/organizations/CarbonPortal_OrganizationSite'
objectSpecification = 'objectSpecificationWebsite'