[58GS]
name = 'G. O. Sars'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_GOSars'
category_code = '31'
call_sign = 'LMEL'
export = ['ICOS','CMEMS']
creation_date = '2019-03-27T21:01:48Z'
author_list = 'Skjelvan, Ingunn'

[LMEL]
platform_id = '58GS'


[26NA]
name = 'Nuka Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26NA'
category_code = '31'
call_sign = 'OXYH2'
export = ['ICOS','CMEMS']
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Becker, Meike; Olsen, Are'

[OXYH2]
platform_id = '26NA'

[65DK]
name = 'Cap San Lorenzo'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_VOS%20France-Brazil'
category_code = '32'
call_sign = 'OXOF2'
export = ['ICOS','CMEMS']
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Lefèvre, Nathalie'

[OXOF2]
platform_id = '65DK'


[SD1030]
name = 'Saildrone 1030'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1030'
category_code = '3B'
call_sign = '5801955'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

[5801955]
platform_id = 'SD1030'


[SD1053]
name = 'Saildrone 1053'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1053'
category_code = '3B'
call_sign = '1801573'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

[1801573]
platform_id = 'SD1053'

[48MB]
name = 'PALOMA'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_PALOMA'
category_code = ''
call_sign = ''
export = ['ICOS']
creation_date = '2020-05-20T00:00:00Z'
author_list = ''

[11SS]
name = 'Simon Stevin'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_11SS'
category_code = '31'
call_sign = 'ORBS'
export = ['ICOS','CMEMS']
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'

[ORBS]
platform_id = '11SS'
