# Old ICES code for G O Sars, deprecated 2018 at ICES, stopped here Jan 2021
[58GS]
name = 'G. O. Sars'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_GOSars'
category_code = '31'
call_sign = 'LMEL'
creation_date = '2019-03-27T21:01:48Z'
author_list = 'Skjelvan, Ingunn'
NRT = 'False'

	[58GS.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

# New ICES code for G O Sars - in use from Jan 2021
[58G2]
name = 'G. O. Sars'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_GOSars'
category_code = '31'
call_sign = 'LMEL'
creation_date = '2021-01-20T09:24:23Z'
author_list = 'Skjelvan, Ingunn'
NRT = 'True'

	[58G2.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[LMEL]
	platform_id = '58G2'


[26NA]
name = 'Nuka Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26NA'
category_code = '31'
call_sign = 'OXYH2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[26NA.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXYH2]
	platform_id = '26NA'

[26RA]
name = 'Tukuma Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26RA'
category_code = '31'
call_sign = 'OYTR2'
creation_date = '2021-01-01T00:00:00Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[26RA.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OYTR2]
	platform_id = '26RA'

[65DK]
name = 'Cap San Lorenzo'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_VOS%20France-Brazil'
category_code = '32'
call_sign = 'OXOF2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Lefèvre, Nathalie'

	[65DK.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXOF2]
	platform_id = '65DK'


[SD1030]
name = 'Saildrone 1030'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1030'
category_code = '3B'
call_sign = '5801955'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[5801955]
	platform_id = 'SD1030'


[SD1053]
name = 'Saildrone 1053'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1053'
category_code = '3B'
call_sign = '1801573'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[1801573]
	platform_id = 'SD1053'

[48MB]
name = 'PALOMA'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_PALOMA'
category_code = ''
call_sign = ''
export = ['ICOS']
creation_date = '2020-05-20T00:00:00Z'
author_list = ''

[11SS]
name = 'Simon Stevin'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_11SS'
category_code = '31'
call_sign = 'ORBS'
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'
NRT = 'True'

	[11SS.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[ORBS]
	platform_id = '11SS'

[74FS]
name = 'Porcupine Abyssal Plain'
submitter_id = 'OTC'
cp_url = ''
category_code = ''
call_sign = ''
creation_date = '2022-03-11T00:00:00Z'
author_list = ""
affiliation = ''
NRT = 'True'

	[74FS.export]
	NRT = []
	L2 = []

