# New ICES code for G O Sars - in use from Jan 2021
[NO-SOOP-G__O__Sars]
platform_code = '58G2'
name = 'G.O.Sars'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_GOSars'
category_code = '31'
call_sign = 'LMEL'
creation_date = '2021-01-20T09:24:23Z'
author_list = 'Skjelvan, Ingunn'
NRT = 'True'

	[NO-SOOP-G__O__Sars.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[LMEL]
	platform_id = '58G2'

[NO-SOOP-Nuka__Arctica]
platform_code = "26NA"
name = 'Nuka Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26NA'
category_code = '31'
call_sign = 'OXYH2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[NO-SOOP-Nuka__Arctica.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXYH2]
	platform_id = '26NA'

[NO-SOOP-Tukuma__Arctica]
platform_code = "26RA"
name = 'Tukuma Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26RA'
category_code = '31'
call_sign = 'OYTR2'
creation_date = '2021-01-01T00:00:00Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[NO-SOOP-Tukuma__Arctica.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OYTR2]
	platform_id = '26RA'

[FR-SOOP-France-Brazil]
platform_code = "65DK"
name = 'Cap San Lorenzo'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_VOS%20France-Brazil'
category_code = '32'
call_sign = 'OXOF2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Lefèvre, Nathalie'

	[FR-SOOP-France-Brazil.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXOF2]
	platform_id = '65DK'


[SailDrone__1030]
platform_code = "SD1030"
name = 'Saildrone 1030'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1030'
category_code = '3B'
call_sign = '5801955'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[5801955]
	platform_id = 'SD1030'


[SailDrone__1053]
platform_code = "SD1053"
name = 'Saildrone 1053'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1053'
category_code = '3B'
call_sign = '1801573'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[1801573]
	platform_id = 'SD1053'

[BE-SOOP-Simon-Stevin]
platform_code = "11SS"
name = 'Simon Stevin'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_11SS'
category_code = '31'
call_sign = 'ORBS'
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'
NRT = 'True'

	[BE-SOOP-Simon-Stevin.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[ORBS]
	platform_id = '11SS'

[BE-FOS-Thornton__Buoy]
platform_code = "1199"
name = 'Thornton Buoy'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_1199'
category_code = '41'
call_sign = ''
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'
NRT = 'True'

	[BE-FOS-Thornton__Buoy.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

[58US]
name = 'Kronprins Haakon'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_58US'
category_code = '31'
call_sign = '3YYQ'
creation_date = '2020-11-17T17:01:34Z'
author_list = 'Fransson, Agneta; Granskog, Mats; Åberg, Petter'
affiliation = 'Norwegian Polar Institute'
NRT = 'False'

	[58US.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

[BHNQ]
name = 'Trans Carrier'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_TCarrier'
category_code = '31'
call_sign = 'C6RM5'
creation_date = '2020-05-05T00:00:00Z'
author_list = 'Omar, Abdirahman; Skjelvan, Ingunn; de Lange, Tor'
affiliation = 'NORCE Norwegian Research Centre AS'
NRT = 'True'

  [BHNQ.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[74FS]
name = 'PAP'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_74FS'
category_code = '41'
call_sign = ''
creation_date = '2022-09-27T00:00:00Z'
author_list = 'Hartman, Sue; Lampitt, Richard'
affiliation = 'National Oceanography Centre, UK'
NRT = 'True'

  [74FS.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[DE-SOOP-Finnmaid]
platform_code = "34FM"
name = 'Finnmaid'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_BALTIC-VOS'
category_code = '31'
call_sign = 'OJMI'
creation_date = '2022-09-27T00:00:00Z'
author_list = 'Glockzin, Michael; Rehder, Gregor'
affiliation = 'Leibniz Institute for Baltic Sea Research' 
NRT = 'False'

  [DE-SOOP-Finnmaid.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

