[QuinCe]
url='%quince_url%'
user='%nrt_api_user%'
password='%nrt_api_password%'

[Database]
location='nrt.sqlite'

[FTP]
server='%nrt_ftp_server%'
user='%nrt_ftp_user%'
password='%nrt_ftp_password%'
dir='%nrt_ftp_folder%'
